# This is the project specific Settings.yml file.
# Place Sphinx specific build information here.
# Settings given here will replace the settings of 'conf.py'.

---
conf.py:
  copyright: 2014-2024
  project: Metadata and Content Analysis Service
  version: 2.5
  release: 2.5.1
  latex_documents:
  - - Index
    - extractor.tex
    - Metadata and Content Analysis Service
    - Xavier Perseguers
    - manual
  latex_elements:
    papersize: a4paper
    pointsize: 10pt
    preamble: \usepackage{typo3}
  latex_show_pagerefs: True
...
